### ISSUE TITLE
Make link in email clickable

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_EventManagement#105]
Currently, the link to view or change the registration is just pure text. Would be nice to have it as a link (before the mail to register for the VV is send).

![grafik](https://user-images.githubusercontent.com/26480843/208051850-798268cf-19e3-40a2-915d-c6ef48ffc2ba.png)

**Comment by geofranzi** [comment]
Adding clickable links increases the chance of being detected as SPAM ... not sure if we should do this.

**Comment by aostrow** [comment]
Ok, do you know if there exists any general rule/advise?
