### ISSUE TITLE
Edit existing registration does not work

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_EventManagement#106]
If I want to edit (correct) an email as an admin, it does not work. 
There will be send a mail with/to the new mail BUT the window keep open and does not jump to the event. Also no changes are visible if I open the registration again.

**Comment by aostrow** [comment]
Also, other changes do not work.

**Comment by aostrow** [comment]
Ok, scheint nur auf dem Testserver mit den existierenden Events so zu sein. Warum?
Aus irgendwelchen Gründen wurde dort auch eine Registrierung in der Warteliste geändert. Dort gibt es gar kein Edit-Button. Ich denke auch, dass ich oben eine Registrierung angepasst hatte.

**Comment by EleonoraPetzold** [comment]
Ging bei mir auch auf dem testserver, schließe das issue vorerst.
