### ISSUE TITLE
Delete Event does not work

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_EventManagement#125]
below Manage Events

![grafik](https://github.com/bexis/Module_EventManagement/assets/26480843/dc397bab-bd68-4f42-b753-6ac4cf95b9d9)

**Comment by EleonoraPetzold** [comment]
The event can currently only be deleted if it has no registrations. Should it also go at the point with?

**Comment by aostrow** [comment]
Should at least give feedback instead of throwing an error. Or make the icon different and have a mouse-over message telling it.
