### ISSUE TITLE
Check edit event registration

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_EventManagement#17]
Ich habe mich registriert und wollte danach eine zweite Registrierung machen. Da ist erstmal meine erste Registrierung aufgepoppt. Diese habe ich geschlossen (durch Save), habe vorher den Platzhalter bei den Additional Infos gelöscht. Dieses wurde nicht übernommen sondern es wurde einfach wieder mein "hab ich keine" stehen gelassen. Also Speicherung ohne Übernahme der Änderung. Dennoch habe ich eine Mail bekommen, ich hätte geändert, inhaltlich ist aber das gleiche drin wie bei der ersten Bestätigung.

**Comment by EleonoraPetzold** [comment]
Tritt so nicht mehr auf. Code wurde seit dem auch noch mal verändert. Wenn man in Bexis eingeloggt ist kann man sich sowieso nicht noch mal unter dem selben Account registirieren.
