### ISSUE TITLE
Waiting list feature: participants limitation reached. 

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_EventManagement#33]
- [x] activate waiting list in event config
- [x] define how many places are on the waiting list or if it's unlimited
- [x] handle waiting list limitation, if the waiting list is reached then closes registration 

- [x] waiting list for each event if it is activated
- [x] the possibility to move someone from the waiting list to the registered list (in show event)

- [x] inform the person when they are on waiting list
- [x] inform the person if they are moved to the registered list
 
If no waiting list is activated and a number of participants are limited then no new registrations are possible when the limit is reached.

**Comment by EleonoraPetzold** [comment]
We want a waiting list feature with a specific number of waiting list places. This number should be defined at the event. After this number is reached no registrations possible.

**Comment by EleonoraPetzold** [comment]
- [ ] close event if participants' limitation is set and reached and no waiting list is activated. 
- [ ] when registrations are deleted waiting list places automatically move up
- [ ] once the event is closed because all places are occupied incl. waiting list, the event should remain closed

**Comment by CFuerstenau** [comment]
Test CF 15.03.

- [ ] keine Mail erhalten, dass ich auf der Warteliste bin
- [ ] keine Mail erhaltenm, als ich meine Anmeldung (die auf der Warteliste war) gelöscht habe
- [ ] unter show reservation könnte in der Spalte "deleted" yes/no stehen statt false/true
- [ ] warum kann ich meine Anmeldung ohne Passwort löschen, aber zum Ändern benötige ich ein Passwort?
