### ISSUE TITLE
Download Metadata button doesn't work

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_EventManagement#63]
- Create a new event by leaving Allow edit checkbox unchecked
- Register the event
- Click View registration and enter the password
- Click Download Metadata 

Result: 
It seems the Download Metadata button doesn't work or it is unnecessary.

![err](https://user-images.githubusercontent.com/66725469/123992018-83ef0400-d9cb-11eb-9c9c-f0a8621f09ef.png)

**Comment by EleonoraPetzold** [comment]
button is removed
