### ISSUE TITLE
Different persons what to be inform via email about registration

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_EventManagement#7]
and they what download the list of all registrations. We need a option so config this for every event separately.

**Comment by geofranzi** [comment]
What is the difference to the option we have? 
- CC email addresses (split by ,)
- BCC email addresses (split by ,)
- Reply to mail address

BCC email addresses (split by ,)
--




BCC email addresses (split by ,)
--




BCC email addresses (split by ,)
--




BCC email addresses (split by ,)
--




BCC email addresses (split by ,)
--

**Comment by EleonoraPetzold** [comment]
> What is the difference to the option we have?
> 
> * CC email addresses (split by ,)
> * BCC email addresses (split by ,)
> * Reply to mail address

Ye, you are right. we can close that issue.
