### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_EventManagement#73]
![grafik](https://user-images.githubusercontent.com/45873895/133616288-ce12fc32-e424-47cf-b696-6265ce8fc2e6.png)

**Comment by CFuerstenau** [comment]
Kann der Teil nicht ganz weg, denn es steht ja schon oben in der Erklärung
![grafik](https://user-images.githubusercontent.com/45873895/133616523-86acfa80-039a-4d83-8091-d3bf08437755.png)

**Comment by EleonoraPetzold** [comment]
gehört zum Core
