### ISSUE TITLE
Can't delete user accout because user register for an event

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_EventManagement#79]
Ich möchte eine Nutzerin löschen, die scheinbar den Account nicht nutzern möchte. Sie hat sich wahrscheinlich nur angemeldet, um sich beim Albsymposium zu registrieren. Dies verhindert aber, dass ich die Person löschen kann.

user ID: 2850816; Name: nicola

Fehlermeldung: 23503: update or delete on table &quot;users&quot; violates foreign key constraint &quot;fkfbf7efc6cb2e8e28&quot; on table &quot;emm_eventregistrations&quot

![grafik](https://user-images.githubusercontent.com/45873895/138042579-6ce1abdb-d261-46d3-93d0-c3cbddb21b28.png)

**Comment by EleonoraPetzold** [comment]
Hatten wir darüber schon mal gesprochen? Es gibt ja eine Verbindung zw. in BExIS registrierten Nutzer und den Event Registrierungen. Wir können die Eventregistrierung löschen, danach kannst du den Nutzer löschen.

**Comment by CFuerstenau** [comment]
Ja, wir hatten das schon mal besprochen. Ich probiere es gleich mal aus.
