### ISSUE TITLE
Values from Additional Mail Information filed disappear

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_EventManagement#87]
- Click the "Create new Event" button
- Fill in the "Additional Mail Information" field
- Then fill in the required fields
- Click Save
- Click the edit icon for the newly created event
- Check the "Additional Mail Information" field

Result: 

Even the "Additional Mail information" field was filled, it appears empty.

**Comment by EleonoraPetzold** [comment]
It seems that the column is missing in the database. Have you inserted it?

**Comment by bayramliaziz** [comment]
> It seems that the column is missing in the database. Have you inserted it?

I have added the latest Db folder, LanguageFiles, and Emm.Settings.xml to my workspace. Other than that I haven't inserted anything to the database.

**Comment by CFuerstenau** [comment]
we currently have the same problem

**Comment by EleonoraPetzold** [comment]
no issue here ... everything is fine
