### ISSUE TITLE
Event Information values are missing for Deutsch

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_EventManagement#89]
- Create a new event
- Fill in the required fields
- Set "SelectedEventLanguage" to "Deutsch"
- Save the even
- Click the "Register" button under "Show Reservations"
- Enter password
- Check "Event Information"

Result: 

If event language is set to "Deutsch". values from "Event Information" disappear.

![err](https://user-images.githubusercontent.com/66725469/153759773-a823ea16-aff0-449f-9b14-ddbdf3b2c3e3.png)

- Then fill in the required fields
- Click Save

Result:
Even the debugger throws an error, the event is registered.

![err2](https://user-images.githubusercontent.com/66725469/153759880-8e91677b-fd13-422f-b185-f9b5ac9a49b3.png)

**Comment by EleonoraPetzold** [comment]
What scheme did you use? You need a schema in german for this. I can send you a scheme in german.

**Comment by bayramliaziz** [comment]
> What scheme did you use? You need a schema in german for this. I can send you a scheme in german.

I am not sure about this. Maybe you can send it to me. Thanks

**Comment by EleonoraPetzold** [comment]
I think it is a problem of the wrong schema which was used. I will close this issue.
