### ISSUE TITLE
New mail text and header

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_EventManagement#93]
**Header:**

1. BExIS - Event: you have successfully registered for xxx (currently: Registration confirmation for xxx)
2. BExIS - Event: you are on the waiting list for xxx (currently: BExIS - Event fully booked - xxx)
3. BExIS - Event: yyy for xxx (currently BExIS - Moved from the waiting list for xxx)
4. editieren
5. löschen

**Text:**

Text für 1. Fall ist in Ordnung

-----------------------------------------------------------------

Dear xxx xxx,

you are currently on the waiting list for the event xxx. We will inform you as soon as a place becomes available.

Yours sincerely,
BExIS team 

---------------------------------------------------------
Dear xxx xxx,

you are now registered for the event and no longer on the waiting list.

Yours sincerely,
BExIS team

**Comment by aostrow** [comment]
BExIS - Event: Registration successfull/confirmation for xxx
BExIS - Event: Edit of registration successfull for xxx
BExIS - Event: Edit of registration failed for xxx
BExIS - Event: Deleted registration (successfull) for xxx (git es hier ein failed)
BExIS - Event: Waiting list place for xxx

**Comment by EleonoraPetzold** [comment]
> BExIS - Event: Deleted registration

There is no mail for the delete yet, do we want one?

**Comment by EleonoraPetzold** [comment]
@aostrow @CFuerstenau 
All changes are in the json files, please also check the german version. 
The current changes are also in german with translation already in there.

https://github.com/bexis/Workspace/tree/master/Modules/EMM/LanguageFiles

**Comment by aostrow** [comment]
> > BExIS - Event: Deleted registration
> 
> There is no mail for the delete yet, do we want one?

I think so. Also the event admins should get the info.

**Comment by EleonoraPetzold** [comment]
all done
